services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    dockerCommand: ./start.sh # 複文コマンドは使えないことがあるので、代わりに実行権限付きのスクリプトを実行する
    healthCheckPath: /health # main.pyの/healthエンドポイントで疎通確認できたらデプロイ成功
    # preDeployCommand: "alembic upgrade head" # free tierだと使えない
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app-db
          property: connectionString

  - type: web
    name: frontend
    runtime: static
    rootDir: frontend
    staticPublishPath: ./dist
    envVars:
      - key: BACKEND_HOST
        fromService:
          name: backend
          type: web
          property: host
    buildCommand: >
      npm ci &&
      VITE_API_BASE_URL="https://${BACKEND_HOST}.onrender.com" npm run build

databases:
  - name: app-db
    databaseName: outfit_db
    plan: free
